version: '3'
services:
  web:
    build: './web'
    ports:
      - "3000"

  search:
    build: './search'
    ports:
      - "3001"
    depends_on: 
      - db
    environment:
      DB_SCHEMA: MS
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_DATABASE: MS

  books:
    build: './books'
    ports:
      - "3002"
    depends_on: 
      - db
    environment:
      DB_SCHEMA: MS
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_DATABASE: MS

  videos:
    build: './videos'
    ports:
      - "3003"
    depends_on: 
      - db
    environment:
      DB_SCHEMA: MS
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_DATABASE: MS
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: MS
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5433"

  nginx:
    image: nginx:latest
    ports:
      - "8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - books
      - search
      - videos
